default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: root
  password: <%= ENV['db_password'] %>
  timeout: 5000

development:
  <<: *default
  database: solomess_dev

test:
  <<: *default
  database: solomess_dev

production:
  <<: *default
  database: solomess_dev